spring.resources.static-locations=file:/D:/Person/workspace/UNIPICK-PROJECT/UNIPICK/src/main/webapp/resources/
logging.level.org.springframework.web=DEBUG
server.servlet.context-path=/UNIPICK
mail.smtp.username=junesse89@gmail.com
mail.smtp.password=bigucidixqufgyzu
