spring.resources.static-locations=file:/D:/Person/workspace/UNIPICK-PROJECT/UNIPICK/src/main/webapp/resources/
logging.level.org.springframework.web=DEBUG
server.servlet.context-path=/UNIPICK
mail.smtp.username=junesse89@gmail.com
mail.smtp.password=bigucidixqufgyzu

coolsms.api_key=NCSOVN2IBQA010ZH
coolsms.api_secret=0S8DRBKOLFSMKAY9RSCPL2TVT3RJU2K5
coolsms.sender=01063296389